<?php
/**
 * @category  Bunited
 * @package   Bunited\CustomTabs
 * @author    Berin Kozlic - beringgmu@gmail.com
 * @copyright 2019 Berin Kozlic
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \Magento\Framework\View\Element\Template */
?>

<div class="<?= /* @escapeNotVerified */ $block->getData('class'); ?>">
    <?= /* @escapeNotVerified */ $block->getContent(); ?>
    <?= /* @escapeNotVerified */ $block->getChildHtml(); ?>
</div>